apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_API_BASE_URL
          value: "${PRODUCT_API_BASE_URL}"
        - name: ORDER_API_BASE_URL
          value: "${ORDER_API_BASE_URL}"
        - name: CUSTOMER_API_BASE_URL
          value: "${CUSTOMER_API_BASE_URL}"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer