apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: production
    spec:
      containers:
      - name: frontend
        image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_API_BASE_URL
          value: "${PRODUCT_API_BASE_URL}"
        - name: ORDER_API_BASE_URL
          value: "${ORDER_API_BASE_URL}"
        - name: CUSTOMER_API_BASE_URL
          value: "${CUSTOMER_API_BASE_URL}"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    environment: production
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer